//! Byte-for-byte comparison against golden fixtures generated by the
//! reference Python implementation (see `fixtures/generate.py`).

use starprint::dither::{Dither, Grayscale};
use starprint::graphics::{BitImage, Density};
use starprint::{Builder, Impact};

const W: u32 = 37;
const H: u32 = 23;

fn source() -> Grayscale {
    Grayscale::new(W, H, include_bytes!("fixtures/src.bin").to_vec()).unwrap()
}

#[test]
fn dithering_matches_reference() {
    let cases: [(Dither, &[u8]); 4] = [
        (
            Dither::FloydSteinberg { threshold: 128 },
            include_bytes!("fixtures/dither_floyd_steinberg.bin"),
        ),
        (
            Dither::Atkinson { threshold: 128 },
            include_bytes!("fixtures/dither_atkinson.bin"),
        ),
        (
            Dither::Threshold { threshold: 128 },
            include_bytes!("fixtures/dither_threshold.bin"),
        ),
        (
            Dither::Bayer8x8,
            include_bytes!("fixtures/dither_bayer.bin"),
        ),
    ];
    for (dither, expected) in cases {
        assert_eq!(dither.apply(&source()).pixels(), expected, "{dither:?}");
    }
}

#[test]
fn bit_image_serialisation_matches_reference() {
    let dithered = Dither::FloydSteinberg { threshold: 128 }.apply(&source());
    let bitmap = dithered.to_bitmap();

    for (density, expected) in [
        (
            Density::Single,
            include_bytes!("fixtures/bit_image_single.bin").as_slice(),
        ),
        (
            Density::Double,
            include_bytes!("fixtures/bit_image_double.bin").as_slice(),
        ),
    ] {
        let image = BitImage::new(bitmap.clone(), density).unwrap();
        let doc = Builder::<Impact>::empty().bit_image(&image).build();
        assert_eq!(doc.as_bytes(), expected, "{density:?}");
    }
}
